### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by SenadM** [skodaconnect/homeassistant-myskoda#175]
all my entities are unavailable. Log below. 

This error originated from a custom integration.

Logger: custom_components.myskoda
Source: custom_components/myskoda/__init__.py:41
integration: MySkoda (documentation, issues)
First occurred: 18:52:05 (1 occurrences)
Last logged: 18:52:05

Login with MySkoda failed.
Traceback (most recent call last):
  File "/config/custom_components/myskoda/__init__.py", line 41, in async_setup_entry
    await myskoda.connect(config.data["email"], config.data["password"])
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 123, in connect
    user = await self.get_user()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 262, in get_user
    return (await self.rest_api.get_user(anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 225, in get_user
    data=await self._make_get_request(url),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 95, in _make_get_request
    return await self._make_request(url=url, method="GET")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 85, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/users'

**Comment by dvx76** [comment]
Yeah there was some downtime on the API today apparently. @SenadM please confirm if you're still having issues.

> Would be great if the sensors wouldn’t go to unavailable if the Skoda servers are down, but just keep the last values known.

I believe this is standard behavior for HA integrations. When the API is unavailable the correct status _is_ unknown because we don't actually know the correct current value. For sensors where you want to have the latest known value available at all times there are various ways around this e.g. using trigger or template platforn. E.g. https://community.home-assistant.io/t/remember-last-sensor-value-instead-of-unavailable/391894 or https://community.home-assistant.io/t/sensor-display-last-known-value-instead-of-unavailable/200081 - there are a lot of similar post like this.

**Comment by WebSpider** [comment]
It seems this issue has dissipated, so I'm closing this. Feel free to reopen if there is new information.
