### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by Mocky158** [skodaconnect/homeassistant-myskoda#200]
I would like to ask if there is any possibility to incorporate my own display into the integrity, perhaps other users would also use it.

My display is currently used on the old version where there is a sensor for both individual doors and individual windows.
I created pictures for this so that they would be updated according to the condition of the car.

[Enyaqcode.txt](https://github.com/user-attachments/files/17662431/Enyaqcode.txt)
[Enyaq.zip](https://github.com/user-attachments/files/17662125/Enyaq.zip)
![homeassist](https://github.com/user-attachments/assets/285fd83e-251e-4c30-83f1-fa82189b88af)

**Comment by Mocky158** [comment]
VIN I have removed

I know that it is enough to just transfer the entities with vin for new ones, but more people write to me that they would also like to use this view, but copying a file with images, etc. is complicated for them, so I thought if it could somehow be incorporated into this integrity.

**Comment by WebSpider** [comment]
This is currently not our focus (and personally I am not knowledgeable about frontend things in HA), but I also do not see a problem to house this within this organisation.

We would need someone to make sure the custom card (because that's what it is, I think?) keeps working with recent HA versions, and who likes tidy code ;-)

**Comment by Tomanic-glitch** [comment]
@Mocky158 I very much like the idea and would like to use something like this as well since my car supports these entities too. It would be probably more logical to have it incorporated in one of the custom car cards though, like the excellent vehicle status card I'm personally using to display vehicle information:

https://github.com/ngocjohn/vehicle-status-card

I know the developer of the card is very responsive and it might be good idea to contact him with suggestion of implementing this feature. I will be happy to do so if you want.

**Comment by dvx76** [comment]
Yeah I think we'd want this to live in it's own project in Github and own integration in HACS/HA. I think it has to be separate for HACS anyway. This might be useful: https://github.com/home-assistant-tutorials

Let us know when you have a first version ready and we can add a new project for it in this org. Maybe `myskoda-cards` 🤷

**Comment by dvx76** [comment]
I'm going to closed this since there is no work to be done in the integration itself or library. If someone wants to start a project to deliver custom frontend cards we can create a new project for this in the skodaconnect org.
