### ISSUE TITLE
Add Parking Time Sensor

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#246]
This is a template issue from the project to get more SkodaConnect sensors into `homeassistant-myskoda`.

**Sensor**
Parking Time

**Last known status**
No support in MySkoda API's discovered yet

**Comment by prvakt** [comment]
probably not available in new MySkoda API, old API was using time from getParkingPosition() request, but new API doesn't return any time in this request, just address and GPS coordinates

**Comment by tiefflieger666** [comment]
Hi,

before I open an additional issue - can you get a binary sensor for "moving" as in the "old" SkodaConnect app?

Because this would solve the issue with missing parking sensor - it would be easy to create a automation based on eg.  moving FALSE for more then 10 minutes.

Addtional too that - I would need the binary moving sensor also for some already existing automations (BTW - the old intergration still works), where I calculate the trips (adding timestamps and odometer etc to google sheets - trigger is moving false) - but I can't find if such a binary sensor is or will be avaliable.

rgd

**Comment by dvx76** [comment]
@tiefflieger666 you can use the device tracker which will have the location/state `vehicle_in_motion` when the car is moving. See #206 (and #234 )

**Comment by dvx76** [comment]
@WebSpider should be just close this issue? I don't know if having issues for features which Skoda my or may not add to the API is that useful. Also the current device tracker should already provide the same info (last update timestamp of the entity = parking time)

**Comment by WebSpider** [comment]
I've added a column in the project where we will move these to, so we still have the observability
