### ISSUE TITLE
unlock - lock ( kodiaq) no change in status

### ISSUE THREAD

**Issue by JanKraslice** [skodaconnect/homeassistant-myskoda#308]
Pressing lock in the controls effectively locks the vehicle, but the status in Home assistant does not change and still reports unlocked! 

Same with the reverse procedure vehicle locked I press unlock in the controls the vehicle is physically unlocked but the status in HM does not change to unlocked 
![17 11 2024](https://github.com/user-attachments/assets/6fa2022a-cf9c-4166-b6dc-8eaa36812da6)

**Comment by WebSpider** [comment]
This can take up to 4 minutes atm

**Comment by WebSpider** [comment]
Elaborating a bit on this, for future reference:

- In order to not to hit the limit of sending too many commands to your car, we limit the amount of "set" commands (which includes the lock, but also honk, flash and AC changes) to one every 30 seconds
- When we send the command, we have to wait for the car to reply. We have observed this can take up to 4 minutes if the car is in sleep-mode (the name of this mode differs per model)
- When we get a response from the car, we try to get a new status for the car. Again in order not to hit limits imposed by Skoda, this can take 30s before the actual request is made

We are exploring how to make this better/quicker, but our main focus is not to get you locked out of the API for 24 hours, when you hit limits imposed by Skoda, or make the car stop responsing to commands until you start the engine.
