### ISSUE TITLE
Add energy class for Ladeleistung (Enyaq)

### ISSUE THREAD

**Issue by gruessung** [skodaconnect/homeassistant-myskoda#323]
Car: Skoda Enyaq

Please add sensor.skoda_enyaq_ladeleistung to home assistant energy class. Actually it's not possible to use this sensor in an intragralhelper to add my car into HA energy dashboard.

**Comment by gruessung** [comment]
@dvx76  HA didn't let me select the charging power sensor for a new integralsensor :) 
I already have one from the old Skoda integration.

**Comment by gruessung** [comment]
@dvx76 Thats weird!
![grafik](https://github.com/user-attachments/assets/51517094-426d-433e-b2d6-8a09ce4174b5)


As you can see i'm not able to choose any sensor starting by sensor.skoda*

**Comment by WebSpider** [comment]
@dvx76 would it be an idea to derive the sensor by default in the integration?

**Comment by dvx76** [comment]
Mostly note-to-self: we could _maybe_ include an entity which subclasses `homeassistant.components.integration.sensor.IntegrationSensor` and sets it up with the `charging_power` sensor. I don't know if this is a good idea 😄 . Would definitely not look into calculating the value ourselves when HA has this feature out of the box.

**Comment by dvx76** [comment]
Looked into this some more and the idea above feels very hacky, if it would even work at all. The integration doesn't keep track of previous values. HA does. So adding an integration sensor in HA as documented in this issue is the right approach IMO. If there are recurring requests for this we could add some documentation/note in the README.
