### ISSUE TITLE
Add VIN number and/or integration name to ID of sensors

### ISSUE THREAD

**Issue by arjanvroege** [skodaconnect/homeassistant-myskoda#57]
Currently all sensors have no link to the device and/or the integration. Example is that the milage sensor is sensor.milage and door sensor is binary_sensor.doors. It would be better if the sensors get a link to the skodaconnect integration or to the device (car) itself. So I would suggest one of these sensor names:

- sensor.skodaconnect.milage
- sensor.vin_number.milage

**Comment by WebSpider** [comment]
The sensors have a link to the device and the device has a link to the integration, however it indeed is not in the name. This hierarchy for instance is displayed when you go to Settings > Integrations > MySkoda.

I think what you mean here is change the default name of the sensor to include the VIN, am I understanding that correctly?

**Comment by arjanvroege** [comment]
I'm trying to clarify it with some screenshots. Take for example the last updated sensor. The sensor within the integration has the following entity_id:
![image](https://github.com/user-attachments/assets/5dea8b5a-dd05-42d6-ae73-419f3e870a54)
So if I search for updated I find the sensor.last_updated as entity ID but I'm not sure if this is the one for the SKODA integration. 

Looking to other integrations they have added some identification in relation to the device in the entity_id:
![image](https://github.com/user-attachments/assets/700f4511-4bad-439b-9877-fe400ea77895)

**Comment by WebSpider** [comment]
Thanks. All clear! :+1:

**Comment by WebSpider** [comment]
Small update: In order to make this possible, we will have to rewrite some essential parts of the integration as the for HA important `unique_id` is calculated off of this.

**Comment by dvx76** [comment]
With the old integration I never found the VIN being part of the entity name (is that the same as the `unique_id` ?) to be particularly appealing. So I'm definitely not in favor of having the VIN in there.

Just adding an incrementing number to entity names for additional cars seems even worse though.

From a UX point of view what I think would be ideal is to allow the user to use an alias/nickname for each vehicle the first time, and then use that. So that you end up with, for e.g. `enyaq.sensor.last_updated` and `suberb.sensor.last_updated`.

But that's a bit impractical since it requires additional user interaction.

The next best thing might be to use the `name` or `model` from the garage or info endpoint response?

**Comment by dvx76** [comment]
Ok so our `unique_id` is fine, right? We already have `self._attr_unique_id = f"{vin}_{self.entity_description.key}"` on the base `MySkodaEntity` class.

The problem is with the entity id, which I think is the same as the key, (and name, maybe).

I still like my idea above where `binary_sensor.charger_connected` would become `binary_sensor.enyaq_charger_connected`.

This works, but it would require defining an `__init__()` in every individual entity class. It will also result in the unique_id changing (since it's based on the `entity_description.key`. Ideally I guess the unique_id would remain the same. Feels like there must be a better way to do this ...

```python
from slugify import slugify

class ChargerConnected(AirConditioningBinarySensor):
    """Detects if the charger is connected to the car."""

    def __init__(
        self,
        coordinator,
        vin,
    ):
        vehicle_name = coordinator.data.vehicle.info.name
        vehicle_name_slug = slugify(vehicle_name, separator="_")
        self.entity_description = BinarySensorEntityDescription(
            key=f"{vehicle_name_slug}_charger_connected",
            name=f"{vehicle_name} Charger Connected",
            device_class=BinarySensorDeviceClass.PLUG,
            translation_key="charger_connected",
        )
        super().__init__(coordinator, vin)
```

**Comment by dvx76** [comment]
The entity names and IDs will include the device name, which is the vehicle title (e.g. Skoda Enyaq), not the VIN. The VIN is still used in the entity unique_ids but is impractical in entity names and ids. Using the device name is also the standard approach in HA.

Example:

Before:

```
entitiy_id = sensor.charger_connected
name = Charger Connected
```

After:

```
entitiy_id = sensor.skoda_enyaq_charger_connected
name = Skoda Enyaq Charger Connected
```

To get the new names and IDs users will need to delete their existing MySkoda device(s) (Hubs) and add them again.
